apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: rsk9946/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/components/*.js'
            dest: .
    - image: rsk9946/comments
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: rsk9946/event-bus
      context: event-bus
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: rsk9946/moderation
      context: moderation
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: rsk9946/posts
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: rsk9946/query
      context: query
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
